### ISSUE TITLE
Download speed is very slow.

### ISSUE THREAD

**Issue by yyms3275** [acmo0/Android-Youtube-Downloader#2]
I confirmed the operation.
But the download speed was very slow!
Can't download fast?

**Comment by acmo0** [comment]
Hello @yyms3275 I know that the download speed was relatively slow ( about 300 kB/second ).
I think that the download speed is a problem of youtube-dl but I'm not sure about that. I'll try to fix this. 
However what is your download speed and are you sure that it's the app which limit the download speed ?

**Comment by yyms3275** [comment]
> Hello @yyms3275 I know that the download speed was relatively slow ( about 300 kB/second ). I think that the download speed is a problem of youtube-dl but I'm not sure about that. I'll try to fix this. However what is your download speed and are you sure that it's the app which limit the download speed ?

I also searched for the following problem. But I don't know exactly what to fix.

"Since summer 2021, YouTube has started serving media URLs with a query parameter such as ...&n=SXiXBH-xzrjeioPN&.... This now appears to be the default behaviour. Unless the value of this parameter is transformed according to an algorithm delivered in the site player JS, the download speed for the URL is throttled to ~50kB/s."

https://github.com/ytdl-org/youtube-dl/issues/29326
https://github.com/ytdl-org/youtube-dl/pull/30184

**Comment by acmo0** [comment]
A solution is to use the youtube-api python3 module but if I do that, all users will have to generate an API key. I can also try to offer both solutions : youtube-dl and to generate a youtube API key

**Comment by yyms3275** [comment]
> A solution is to use the youtube-api python3 module but if I do that, all users will have to generate an API key. I can also try to offer both solutions : youtube-dl and to generate a youtube API key

I also do download related services, but the method through the API is not a perfect solution. I also don't use the API method. I am also searching for the part related to speed limit. If I ever find a solution, I'll share it.

**Comment by acmo0** [comment]
> I also do download related services, but the method through the API is not a perfect solution. I also don't use the API method. I am also searching for the part related to speed limit. If I ever find a solution, I'll share it.

Ok thank you. I'll try to find a way to download with a better speed limit to.

**Comment by acmo0** [comment]
This issue is solved by the v1.2 release.
Thank you for opening this issue @yyms3275
